### ISSUE TITLE
.

### ISSUE THREAD

**Issue by haxsurus** [MhankBarBar/termux-wabot#27]
All bots have stopped working, a bug has appeared in axios security. 

up to date, audited 333 packages in 9s

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

And at the time of Install, the bot no longer works even if you do the command to fix the error 
![Screenshot_2021-01-05-18-51-11](https://user-images.githubusercontent.com/52586147/103708462-018b0780-4f87-11eb-8367-093c3c2cb81d.png)

**Comment by NazwaS** [comment]
Try
```bash
npm cache verify
npm cache clean -f
npm audit fix -f
```
