### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by muhifni** [MhankBarBar/termux-wabot#30]
internal/modules/cjs/loader.js:798
    throw err;
    ^

Error: Cannot find module 'fs/promises'
Require stack:
- /data/data/com.termux/files/home/termux-wabot/node_modules/imgbb-uploader/lib/cjs/validateInput.js
- /data/data/com.termux/files/home/termux-wabot/node_modules/imgbb-uploader/lib/cjs/index.js
- /data/data/com.termux/files/home/termux-wabot/lib/functions.js
- /data/data/com.termux/files/home/termux-wabot/index.js

**Comment by HAFizh-15** [comment]
npm i fs.promises atau npm i fs/promises cbin mana yang work
