### ISSUE TITLE
Broken Scan Qr

### ISSUE THREAD

**Issue by Suryapardana** [MhankBarBar/termux-wabot#33]
WARNabar [2021-01-07 14:55:29.938 +0000] (11552): connect attempt 1 failed: BaileysError: Unexpected error in login
    error: {
      "name": "BaileysError",
      "status": 401,
      "context": {
        "response": {
          "status": 401
        },
        "status": 401
      }
    }
    class: "Baileys"
(node:11552) UnhandledPromiseRejectionWarning: BaileysError: Unexpected error in login
    at WAConnection.authenticate (/data/data/com.termux/files/home/deca/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:98:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/deca/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:106:40)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MhankBarBar** [comment]
first delete the previous login session, if you just run the script again. Sorry, my English is bad
