### ISSUE TITLE
Simi API 

### ISSUE THREAD

**Issue by lxndr-rl** [MhankBarBar/termux-wabot#55]
When you use simsimi api it returns Piracy Message.
![image](https://user-images.githubusercontent.com/47733425/107863728-a3beca80-6e24-11eb-8cda-d3447c87d56c.png)

**Comment by fdciabdul** [comment]
pake cookies simi emang pasti kena limit , beli aja api key nya :v

**Comment by lxndr-rl** [comment]
that api is somewhat expensive.  do you know any more?

**Comment by fdciabdul** [comment]
> that api is somewhat expensive. do you know any more?

i've been used simsumi.herokuapp.com , but it doesn't work anymore
