### ISSUE TITLE
Help bang 

### ISSUE THREAD

**Issue by MuhammadRestu999** [MhankBarBar/termux-wabot#81]
Emrorr
![Screenshot_2021-07-25-18-45-06-87_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83255517/126897843-d7df3261-6b2d-4389-a958-16f4c4b390ab.jpg)

[localhost@u0_a207] - [~/termux-wabot] $ bash install.sh
Hit:1 https://packages.termux.org/apt/termux-main stable InRelease
Hit:2 https://packages.termux.org/apt/termux-games games InRelease                                                              Hit:3 https://packages.termux.org/apt/termux-science science InRelease                                                          Hit:4 https://packages.termux.org/apt/termux-x11 x11 InRelease  Reading package lists... Done                                   Reading package lists... Done                                   Building dependency tree... Done                                Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done                                   Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (4.4).
libwebp is already the newest version (1.2.0).
nodejs is already the newest version (14.15.4-2).               tesseract is already the newest version (4.1.1).
wget is already the newest version (1.21.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2021-07-25 18:38:41--  https://github.com/tesseract-ocr/tessdata/blob/master/ind.traineddata?raw=true
Resolving github.com... 52.74.223.119                           Connecting to github.com|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata [following]
--2021-07-25 18:38:42--  https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata [following]
--2021-07-25 18:38:42--  https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8279230 (7.9M) [application/octet-stream]
Saving to: ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’

/data/data/com. 100%[=======>]   7.90M   299KB/s    in 26s

2021-07-25 18:39:08 (314 KB/s) - ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’ saved [8279230/8279230]

> canvas@2.8.0 install /data/data/com.termux/files/home/termux-wabot/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xau', not found
gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.9.190+
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fa

**Comment by ThisMe124** [comment]
> Emrorr
> ![Screenshot_2021-07-25-18-45-06-87_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83255517/126897843-d7df3261-6b2d-4389-a958-16f4c4b390ab.jpg)
> 
> [localhost@u0_a207] - [~/termux-wabot] $ bash install.sh
> Hit:1 https://packages.termux.org/apt/termux-main stable InRelease
> Hit:2 https://packages.termux.org/apt/termux-games games InRelease Hit:3 https://packages.termux.org/apt/termux-science science InRelease Hit:4 https://packages.termux.org/apt/termux-x11 x11 InRelease Reading package lists... Done Reading package lists... Done Building dependency tree... Done Reading state information... Done
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done Building dependency tree... Done
> Reading state information... Done
> ffmpeg is already the newest version (4.4).
> libwebp is already the newest version (1.2.0).
> nodejs is already the newest version (14.15.4-2). tesseract is already the newest version (4.1.1).
> wget is already the newest version (1.21.1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> --2021-07-25 18:38:41-- https://github.com/tesseract-ocr/tessdata/blob/master/ind.traineddata?raw=true
> Resolving github.com... 52.74.223.119 Connecting to github.com|52.74.223.119|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata [following]
> --2021-07-25 18:38:42-- https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata
> Reusing existing connection to github.com:443.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata [following]
> --2021-07-25 18:38:42-- https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata
> Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
> Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 8279230 (7.9M) [application/octet-stream]
> Saving to: ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’
> 
> /data/data/com. 100%[=======>] 7.90M 299KB/s in 26s
> 
> 2021-07-25 18:39:08 (314 KB/s) - ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’ saved [8279230/8279230]
> 
> > canvas@2.8.0 install /data/data/com.termux/files/home/termux-wabot/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
> Package xproto was not found in the pkg-config search path.
> Perhaps you should add the directory containing `xproto.pc' to the PKG_CONFIG_PATH environment variable Package 'xproto', required by 'xau', not found gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack at ChildProcess.onCpExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Linux 4.9.190+
> gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fa

npm install

**Comment by MuhammadRestu999** [comment]
> > Emrorr
> > ![Screenshot_2021-07-25-18-45-06-87_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83255517/126897843-d7df3261-6b2d-4389-a958-16f4c4b390ab.jpg)
> > [localhost@u0_a207] - [~/termux-wabot] $ bash install.sh
> > Hit:1 https://packages.termux.org/apt/termux-main stable InRelease
> > Hit:2 https://packages.termux.org/apt/termux-games games InRelease Hit:3 https://packages.termux.org/apt/termux-science science InRelease Hit:4 https://packages.termux.org/apt/termux-x11 x11 InRelease Reading package lists... Done Reading package lists... Done Building dependency tree... Done Reading state information... Done
> > Calculating upgrade... Done
> > 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> > Reading package lists... Done Building dependency tree... Done
> > Reading state information... Done
> > ffmpeg is already the newest version (4.4).
> > libwebp is already the newest version (1.2.0).
> > nodejs is already the newest version (14.15.4-2). tesseract is already the newest version (4.1.1).
> > wget is already the newest version (1.21.1).
> > 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> > --2021-07-25 18:38:41-- https://github.com/tesseract-ocr/tessdata/blob/master/ind.traineddata?raw=true
> > Resolving github.com... 52.74.223.119 Connecting to github.com|52.74.223.119|:443... connected.
> > HTTP request sent, awaiting response... 302 Found
> > Location: https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata [following]
> > --2021-07-25 18:38:42-- https://github.com/tesseract-ocr/tessdata/raw/master/ind.traineddata
> > Reusing existing connection to github.com:443.
> > HTTP request sent, awaiting response... 302 Found
> > Location: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata [following]
> > --2021-07-25 18:38:42-- https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/ind.traineddata
> > Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
> > Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
> > HTTP request sent, awaiting response... 200 OK
> > Length: 8279230 (7.9M) [application/octet-stream]
> > Saving to: ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’
> > /data/data/com. 100%[=======>] 7.90M 299KB/s in 26s
> > 2021-07-25 18:39:08 (314 KB/s) - ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’ saved [8279230/8279230]
> > > canvas@2.8.0 install /data/data/com.termux/files/home/termux-wabot/node_modules/canvas
> > > node-pre-gyp install --fallback-to-build
> > 
> > 
> > node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
> > node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
> > node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm64.tar.gz
> > Package xproto was not found in the pkg-config search path.
> > Perhaps you should add the directory containing `xproto.pc' to the PKG_CONFIG_PATH environment variable Package 'xproto', required by 'xau', not found gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1
> > gyp ERR! stack at ChildProcess.onCpExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> > gyp ERR! stack at ChildProcess.emit (events.js:315:20)
> > gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> > gyp ERR! System Linux 4.9.190+
> > gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fa
> 
> npm install

Udah
Tapi sama aja error
